name: blind
channels:
  - conda-forge
  - defaults
dependencies:
  - Flask
  - Flask-Moment
  - Flask-WTF
  - Flask-Login
  - google-api-python-client
  - google-auth
  - numpy=1.16.4
  - pandas
  - python
  - pip
  - python-dotenv
  - networkx
  - pip:
    - flask-bootstrap
    - mod_wsgi
